config/routes.rb
Rails.application.routes.draw do

  devise_for :users


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Defines the root path route ("/")
  # root "posts#index"
  #root to: "lists#index"
  root 'projects#index'

  resources :projects
  resources :tasks
  
  resources :projects do
    # resources :reviews, only: [:create, :destroy]
    resources :reviews
    resources :tasks

  end


  
  resources :movies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: {minimum: 6}
  validates :movie_id, uniqueness: {scope: :list_id, message: "is already in the list"}
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
end

app/models/data_review.rb
class DataReview < ApplicationRecord
  belongs_to :project
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :comments, as: :commentable
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true, presence: true

end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, as: :commentable
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks, dependent: :destroy
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :project
  validates :rating, presence: true
  validates :comment, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project

  enum status: { pending: 0, in_progress: 1, completed: 8 }

  before_save :set_progress_based_on_status
  
  
  private

  def set_progress_based_on_status
    if status == "pending"
      self.progress = 0
    elsif status == "in_progress" && progress < 1
      self.progress = 1
    elsif status == "in_progress" && progress > 7
      self.progress = 7
    elsif status == "completed"
      self.progress = 8
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  
  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
    @review = Review.new(list: @list)
    @movies = @list.movies
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.picture_url = params[:list][:picture_url]
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # lists_controller.rb

  def edit
  @list = List.find(params[:id])
  end

  def update
    if @list.update(list_params)
      redirect_to list_path(@list)
    else
      render :edit, status: :unprocessable_entity
    end
  end


  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :picture_url)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :set_project, only: [:show, :edit, :update, :destroy]
  
    def index
      @projects = Project.all
    end
  
    def show
      @project = Project.find(params[:id])
      @review = @project.reviews.new 
      @tasks = @project.tasks
    end
    
    def new
      @project = Project.new
    end
  
    def create
      @project = Project.new(project_params)
      if @project.save
        redirect_to project_path(@project)
      else
        render :new, status: :unprocessable_entity
      end
    end
  
    def edit
      @project = Project.find(params[:id])
    end
  
    def update
      if @project.update(project_params)
        redirect_to project_path(@project)
      else
        render :edit, status: :unprocessable_entity
      end
    end
   

    def destroy
      @project = Project.find(params[:id])
      @project.destroy
      redirect_to projects_path, notice: 'Project was successfully deleted.'
    end
    

    private
  
    def set_project
      @project = Project.find(params[:id])
    end
  
    def project_params
      params.require(:project).permit(:name, :description, :deadline)
    end
    

  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
  def background_image_url(option)
  case option
  when 'Comedy'
    'https://images.unsplash.com/photo-1543584756-8f40a802e14f?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'
  when 'Drama'
    'https://images.unsplash.com/photo-1612015888543-a4057b56ac17?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'
  when 'Horror'
    'https://images.unsplash.com/photo-1521898461100-618454f89314?q=80&w=2874&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'
  ## Add more cases for each option and its corresponding image URL
  else
    'https://images.unsplash.com/photo-1542204165-65bf26472b9b?q=80&w=2874&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'
  end
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/projects/_form.html.erb
<%= simple_form_for(project) do |f| %>
  <div class="form-group">
    <%= f.label :name, 'Project Name' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :description, 'Project Description' %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :deadline, 'Project Deadline' %>
    <%= f.datetime_local_field :deadline, class: 'form-control' %>
  </div>

  <%= f.submit 'Save Project', class: 'btn btn-primary' %>
<% end %>

app/views/projects/_header.html.erb
<div class="banner-container banner-change">
  <div class="banner-nav-bar">
    <div><h1><i class="fas fa-play"></i>Projct</h1></div>
    <div>
      <ul class="banner-ul">
      <li><%= link_to "Home", root_path, class: "nav-link" %></li> <!-- Home button -->

        <li>Login</li>
        
        <li class="btn-sign">Sign up</li>
      </ul>
    </div>
  </div>
</div>

app/views/projects/edit.html.erb
<%= render 'header' %>

<div class="container">
    <div class="row new-form">
      <div class="col-lg-6 left-bg-list">
      </div>
      <div class="col-lg-6 right-bg" >
      <%= render 'form', project: @project %>
      </div>
  </div>

</div>

app/views/projects/index.html.erb
<!-- In the main page view, such as app/views/projects/index.html.erb -->

<div class="banner-container">
  <div class="banner-nav-bar">
    <div><h2></h2></div>
    <div>
   
    <ul class="banner-ul">
      <li><%= link_to "Home", root_path, class: "nav-link" %></li> 
      <% if user_signed_in? %>
      <%= button_to "Logout", destroy_user_session_path, method: :delete %>

    <% else %>
      <%= link_to "Login", new_user_session_path %>
      <%= link_to "Sign up", new_user_registration_path %>
      <% end %>
    </ul>
    </div>
  </div>
  <div class="banner-info">
    <div>
      <p class="banner-title"><i class="fas fa-tasks"></i> PROJECT MANAGER</p>
      <p class="banner-subtitle">Your Ultimate Project and Task Management Companion!</p>
      <div class="btn-infos">
        <p class="btn-add"><%= link_to "Add Project", new_project_path %></p> 

        <p class="btn-more-info"><%= link_to "Add Task", new_task_path %></p>
        <p class="btn-add"> <%= link_to "View All Tasks", tasks_path %></p>
      </div>
    </div>
  </div>
</div>




<div class="row">
  <% @projects.each do |project| %>
    <div class="col-4 mb-4">
      <div class="project-card-wrapper">
        <div class="project-card border bg-light position-relative">
          <%= link_to project_path(project), class: "text-decoration-none text-center d-block", style: "font-size: 40px; color: black;" do %>
            <%= project.name %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div> <!-- Close the row -->

<%= render 'footer' %>

app/views/projects/new.html.erb
<div class="banner" style="background-image: url('/images/back_new.jpg')">
  <div class="container py-5">
    <div class="row">
      <div class="col-12 col-md-6 offset-lg-3">
        <div class="bg-white rounded p-3 shadow">
          <h3>Create a new project</h3>
          <%= simple_form_for @project do |f| %>
            <%= f.input :name, placeholder: 'Enter project name' %>
            <%= f.input :description, as: :text, placeholder: 'Enter project description' %>
            
            <!-- Manually create a datetime-local input -->
            <div class="form-group">
              <%= f.label :deadline, 'Project Deadline' %>
              <%= f.datetime_local_field :deadline, class: 'form-control' %> <!-- Use standard datetime-local input -->
            </div>
            <div class="form-group">
            <%= label_tag :user_input, 'Assign Users' %>
            <%= text_area_tag :user_input, nil, placeholder: 'Enter user(s) details (e.g., username or email)', class: 'form-control' %>
          </div>



            <div class="text-center">
              <%= f.submit 'Save', class: 'btn btn-success border mt-2 hover' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<%= render 'header' %>

<div class="container">
  <div class="Project-content">
    <div class="row">
      
      <div class="col-lg-6">
        <h2><%= @project.name %> project</h2>
          <div class="btn-style">
            <p><%= link_to "Edit", edit_project_path(@project), class: 'btn-edit' %></p>
            <p>
              <%= link_to "Delete", project_path(@project), 
                          method: :delete, 
                          data: { confirm: "Are you sure you want to delete this project?" }, 
                          class: 'btn-delete' %>
            </p>
          </div>
          <!-- Display the description of the project here -->
          <h2> description:</h2>
          <p class="text-muted" style="font-size: 1.6rem; line-height: 1.6; background-color: white; border: 1px solid #ddd; padding: 10px; border-radius: 8px;">
          <%= @project.description %>
          </p>

          
          </div>
    </div>


   
  </div>
</div>

<hr class="my-5">
<div class="row">
  <div class="col-md-6">
    <h3>Tasks</h3>
    <% @project.tasks.each do |task| %>
      <div class="col-lg-6 task-display-content">
        <div class="task-header-content">
          <p class="task-title h1"><%= task.title %></p>
          <p class="btn-task-edit"><%= link_to "Edit Task", edit_task_path(task) %></p>
        </div>

        <div class="task-status-section">
          <p><strong>Status:</strong> <%= task.status.humanize %></p>
        </div>

        <div class="task-progress-section">
          <p><strong>Progress:</strong> <%= task.progress %>%</p>
        </div>

        <div class="task-project-section">
          <p><strong>Project:</strong> <%= task.project.name if task.project.present? %></p>
        </div>

        <div class="task-description">
          <p><strong>Description:</strong></p>
          <p><%= task.description %></p>
        </div>

        <div class="task-timestamps">
          <p><strong>Created At:</strong> <%= task.created_at.strftime("%B %d, %Y %H:%M") %></p>
          <p><strong>Updated At:</strong> <%= task.updated_at.strftime("%B %d, %Y %H:%M") %></p>
        </div>
      </div>
      <hr>
    <% end %>
  </div>
</div>




<hr class="my-5">
<hr class="my-5">

<div class="row">
  <div class="col-md-6">
    <h3>Reviews</h3>
    <% @project.reviews.each do |review| %>
      <div>
        <% if review.rating.present? %>  <!-- Check if the rating is not nil -->
          <% review.rating.times do %>
            <i class="fas fa-star star-yellow"></i>
          <% end %>
        <% else %>
          <i class="fas fa-star"></i> <!-- If rating is nil, display a default star -->
        <% end %>
    
        <!-- Handle nil created_at -->
        <small><em class="text-muted">
          <% if review.created_at.present? %>
            <%= distance_of_time_in_words_to_now(review.created_at) %> ago
          <% else %>
            <%= "Unknown time" %> <!-- You can replace this with a default message -->
          <% end %>
        </em></small>
        
        <p class="mb-0"><%= review.comment %></p>
        <%= link_to "Delete Review", project_path(@project), class: "btn btn-warning border", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this review?" } %>
      </div>
      <hr> <!-- Add a horizontal line break -->
    <% end %>
    
  </div>

  <div class="col-md-6">
    <div class="border bg-white rounded p-3">
      <h5>Add your review</h5>
      <%= simple_form_for [@project, @review] do |f| %>
        <%= f.input :comment, placeholder: "Add your review here..." %>
        <label for="rating" class="form-label">Select Rating🌟*</label>
        <%= f.input :rating, as: :select, collection: (1..5), required: true, label: false, input_html: { class: "form-select text-warning", data: { controller: "star-rating" } } %>
        <%= f.submit class: "btn btn-success mt-2" %>
      <% end %>
    </div>
  </div>
</div>